### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by AndreaMinato** [maple3142/vuejs-storage#6]
Hi i think it would be nice to have the chance to save some states in sessionStorage and some in localStorage similar to this:
```javascript
plugins: [
  vuejsStorage({
    namespace: 'multistorage',
    localStorageKeys: ['keyA', 'keyB'], //keys to be saved in localStorage
    sessionStorageKeys: ['keyC'],  //keys to be saved in sessionStorage 
  })
]
```
until now i can make it work like that:
```javascript
plugins: [
    vuejsStorage({
      namespace: "storage_session",
      storage: window.sessionStorage, //keys to be saved in sessionStorage 
      keys: ["keyC"], 

    }),
    vuejsStorage({
      namespace: "storage_local",
      keys: ["keyA", "keyB"] //keys to be saved in localStorage
    })
  ]
```

so it works if i declare two plugin one with sessionStorage and one with localStorage and using two different namespace. i don't know what will be the behaviour if i use the same namespace and if i use the same key in both the plugins.

do you think taht this would be possible and that it makes sense? 
In my opinion it would boost your library making tha api far more easy to use .

**Comment by maple3142** [comment]
You can use same namespace in different storage.
Because this plugin use `storage.setItem(namespace,xxx)` and `sotrage.getItem(namespace,xxx)` internally.

**Comment by maple3142** [comment]
Multiple storage option is added in [v2.3.0](https://github.com/maple3142/vuejs-storage/releases/tag/v2.3.0).

And I think I won't implement `localStorageKeys`,`sessionStorageKeys` or something similar.
Because `storage` option accept anything has `getItem` & `setItem`, so you can easily implement your own storage has some extra feature. For example, cache timeout.
So this plugin is not limited to `localStorage` and `sessionStorage` only.

**Comment by AndreaMinato** [comment]
Nice, thank you so much.
